title: Nworm
subtitle: ''      #暂时没用
description: '这个人很懒，什么都没有留下'     
keywords: web,js,php,ghs,anime,yoshino
author: nworm
avatar: //q1.qlogo.cn/g?b=qq&nk=1574242600&s=640
language: zh-Hans
utc: 8
since: 2019-6-21 11:30:00     #世界时

url: https://nworm.icu  #暂时没用
root: /   #暂时没用

listener: 
  visibilitychange:
    enable: true
    show_text: 谢谢您,愿意陪我
    hide_text: 不要离开我,好吗

index_generator:
  per_page: 10

menu:
  Home: /home
  Archives: /archives
  About: /about
  Link: /link
  
link:
  - 染念的笔记|一个神秘的人|https://dyedd.cn/|//q1.qlogo.cn/g?b=qq&nk=1176996982&s=140
  - 時雨の記|一个神秘的人|https://drizzle.vip/|//q1.qlogo.cn/g?b=qq&nk=396823203&s=140
  - 寒枫|一个神秘的人|https://hanfen.run/|//q1.qlogo.cn/g?b=qq&nk=1091044631&s=140
  - 孤丶宇の博客|一个神秘的人|http://www.guyuhomepage.cn/Blog/|//q1.qlogo.cn/g?b=qq&nk=1140246200&s=140
  - XY-LSXG|一个神秘的人|https://xfox.fun|//q1.qlogo.cn/g?b=qq&nk=1912300968&s=140
  - zankyo|我竟从未留意过，这个世界是如此的美丽|https://zankyo.cc/|//zankyo.cc/wp-content/uploads/2017/11/20171127_082530.jpg
  - 布丁の基地|一个神秘的人|https://blog.furryowo.top/|//www.gravatar.com/avatar/c0b4d00a9bd59c430bf76206899c2d3c?s=500&r=X&d=

comment:
  disqus:
    enable: true
    id: nworm

contact:
  github: 1574242600
  twitter: null
  fb: null
  line: null
  stackoverflow: null
  qq: null