# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI

on:
  push:
    branches: [ source ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        persist-credentials: false
        fetch-depth: 0
        node-version: ${{ matrix.node-version }}
    - name: install
      run: |
        git clone https://github.com/1574242600/1574242600.github.io-spa.git .deploy_git
        git submodule update --init --recursive
        npm ci
        cd ./theme/yoshino
        git config pull.rebase false
        git pull
        npm ci
        cd ../../
    - name: build
      run: | 
        npm run build
        cd ./theme/yoshino
        npm run build
        cd ../../
        cp ./theme/yoshino/build/* ./public/ -r
    - name: commit files
      run: |
        mv ./.deploy_git/.git/ ./public/
        cd ./public/
        git config user.name "1574242600"
        git config user.email "1574242600@qq.com"
        git add . 
        git commit -m " Github Actions `date +"%Y-%m-%d %H:%M"`"
    - name: push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        directory: ./public/
        
        
